
-- DOC_Appointer Full Database Tables
-- ---------------------------------

-- PARENT TABLES 

-- 1. Users
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    pass VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20),
    role VARCHAR2(50) NOT NULL
);

-- 2. Admin
CREATE TABLE admin (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id NUMBER NOT NULL,
    role VARCHAR2(50),
    branch_id NUMBER,
    CONSTRAINT fk_admin_users FOREIGN KEY (users_id) REFERENCES users(id)
);

-- 3. Departments
CREATE TABLE departments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    CONSTRAINT fk_dept_admin FOREIGN KEY (admin_id) REFERENCES admin(id)
);

-- 4. Specialization
CREATE TABLE specialization (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    CONSTRAINT fk_spec_admin FOREIGN KEY (admin_id) REFERENCES admin(id)
);

-- 5. Hospital Branches
CREATE TABLE hospital_branches (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    address VARCHAR2(200),
    established_date DATE,
    CONSTRAINT fk_branch_admin FOREIGN KEY (admin_id) REFERENCES admin(id)
);

-- 6. Medications
CREATE TABLE medications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_name VARCHAR2(100) NOT NULL,
    duration VARCHAR2(50),
    dosage VARCHAR2(50)
);

-- 7. Beds
CREATE TABLE beds (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER NOT NULL,
    room_number VARCHAR2(20),
    ward_number VARCHAR2(20),
    type VARCHAR2(50),
    status VARCHAR2(50),
    CONSTRAINT fk_beds_admin FOREIGN KEY (admin_id) REFERENCES admin(id)
);

-- 8. Time Slots
CREATE TABLE time_slots (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id_last NUMBER NOT NULL,
    start_time DATE NOT NULL,
    end_time DATE NOT NULL,
    status VARCHAR2(50),
    last_edited_at DATE,
    type_id NUMBER,
    CONSTRAINT fk_timeslot_admin FOREIGN KEY (admin_id_last) REFERENCES admin(id)
);

-- CHILDREN TABLES

-- 9. Patient
CREATE TABLE patient (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    date_of_birth DATE,
    gender VARCHAR2(10),
    occupation VARCHAR2(50),
    blood_type VARCHAR2(5),
    marital_status VARCHAR2(20),
    address VARCHAR2(200),
    CONSTRAINT fk_patient_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 10. Doctor
CREATE TABLE doctor (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    admin_id NUMBER NOT NULL,
    license_number VARCHAR2(50),
    degrees VARCHAR2(200),
    experience_years NUMBER,
    available_days_times VARCHAR2(200),
    dept_id NUMBER,
    branch_id NUMBER,
    CONSTRAINT fk_doctor_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_doctor_admin FOREIGN KEY (admin_id) REFERENCES admin(id),
    CONSTRAINT fk_doctor_dept FOREIGN KEY (dept_id) REFERENCES departments(id),
    CONSTRAINT fk_doctor_branch FOREIGN KEY (branch_id) REFERENCES hospital_branches(id)
);

-- 11. Doc Specialization
CREATE TABLE doc_specialization (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id NUMBER NOT NULL,
    specialization_id NUMBER NOT NULL,
    CONSTRAINT fk_doc_spec_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(id),
    CONSTRAINT fk_doc_spec_spec FOREIGN KEY (specialization_id) REFERENCES specialization(id)
);

-- 12. Doctors Appointments
CREATE TABLE doctors_appointments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    doctor_id NUMBER NOT NULL,
    appointment_date DATE,
    time_slot_id NUMBER,
    status VARCHAR2(50),
    type VARCHAR2(50),
    CONSTRAINT fk_doctor_appointment_patient FOREIGN KEY (patient_id) REFERENCES patient(id),
    CONSTRAINT fk_doctor_appointment_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(id),
    CONSTRAINT fk_doctor_appointment_timeslot FOREIGN KEY (time_slot_id) REFERENCES time_slots(id)
);

-- 13. Lab Test Appointments
CREATE TABLE lab_test_appointments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    reference VARCHAR2(100),
    doctor_id NUMBER,
    time_slot_id NUMBER,
    test_id NUMBER,
    test_file_url VARCHAR2(200),
    CONSTRAINT fk_lab_patient FOREIGN KEY (patient_id) REFERENCES patient(id),
    CONSTRAINT fk_lab_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(id),
    CONSTRAINT fk_lab_timeslot FOREIGN KEY (time_slot_id) REFERENCES time_slots(id)
);

-- 14. Bed Booking Appointments
CREATE TABLE bed_booking_appointments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_appointment_id NUMBER NOT NULL,
    bed_id NUMBER NOT NULL,
    time_slot_id NUMBER,
    status VARCHAR2(50),
    CONSTRAINT fk_bed_booking_app FOREIGN KEY (doctor_appointment_id) REFERENCES doctors_appointments(id),
    CONSTRAINT fk_bed_booking_bed FOREIGN KEY (bed_id) REFERENCES beds(id),
    CONSTRAINT fk_bed_booking_timeslot FOREIGN KEY (time_slot_id) REFERENCES time_slots(id)
);

-- 15. Prescription
CREATE TABLE prescription (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id NUMBER NOT NULL,
    date_issued DATE,
    chief_complaints VARCHAR2(500),
    investigations VARCHAR2(500),
    required_tests VARCHAR2(500),
    diagnosis VARCHAR2(500),
    history VARCHAR2(500),
    instructions VARCHAR2(500),
    visit_again_at DATE,
    CONSTRAINT fk_prescription_appointment FOREIGN KEY (appointment_id) REFERENCES doctors_appointments(id)
);

-- 16. Prescribed Medications
CREATE TABLE prescribed_med (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id NUMBER NOT NULL,
    medication_id NUMBER NOT NULL,
    CONSTRAINT fk_prescribed_prescription FOREIGN KEY (prescription_id) REFERENCES prescription(id),
    CONSTRAINT fk_prescribed_med FOREIGN KEY (medication_id) REFERENCES medications(id)
);

-- 17. Bills
CREATE TABLE bills (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER NOT NULL,
    appointment_id NUMBER,
    total_amount NUMBER,
    status VARCHAR2(50),
    issue_date DATE,
    CONSTRAINT fk_bills_admin FOREIGN KEY (admin_id) REFERENCES admin(id),
    CONSTRAINT fk_bills_appointment FOREIGN KEY (appointment_id) REFERENCES doctors_appointments(id)
);

-- 18. Bill Receipt
CREATE TABLE bill_recepit (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(500),
    paying_date DATE,
    amount NUMBER,
    paying_method VARCHAR2(50)
);

-- 19. Medical Technician
CREATE TABLE medical_technician (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    admin_id NUMBER NOT NULL,
    degrees VARCHAR2(200),
    experience_years NUMBER,
    dept_id NUMBER,
    branch_id NUMBER,
    CONSTRAINT fk_tech_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_tech_admin FOREIGN KEY (admin_id) REFERENCES admin(id),
    CONSTRAINT fk_tech_dept FOREIGN KEY (dept_id) REFERENCES departments(id),
    CONSTRAINT fk_tech_branch FOREIGN KEY (branch_id) REFERENCES hospital_branches(id)
);

-- 20. Branch Contacts
CREATE TABLE branch_contacts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id NUMBER NOT NULL,
    branch_id NUMBER NOT NULL,
    contact_no VARCHAR2(20),
    type VARCHAR2(50),
    CONSTRAINT fk_branch_contacts_admin FOREIGN KEY (admin_id) REFERENCES admin(id),
    CONSTRAINT fk_branch_contacts_branch FOREIGN KEY (branch_id) REFERENCES hospital_branches(id)
);

-- 21. Emergency Contacts
CREATE TABLE emergency_contacts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER NOT NULL,
    contact_no VARCHAR2(20),
    name VARCHAR2(100),
    relation VARCHAR2(50),
    contact_address VARCHAR2(200),
    CONSTRAINT fk_emergency_patient FOREIGN KEY (patient_id) REFERENCES patient(id)
);

